<?php
return array(
  'css' => [
      "public/frontend/assets/css/bootstrap.min.css",
      "public/frontend/assets/plugins/notifications/css/lobibox.min.css",
      "public/frontend/assets/css/owl.carousel.min.css",
      "public/frontend/assets/css/slick.css",
      "public/frontend/assets/css/magnific-popup.css",
      "public/frontend/assets/css/animate.css",
      "public/frontend/assets/css/jquery-ui.min.css",
      "public/frontend/assets/css/slinky.menu.css",
      "public/frontend/assets/css/plugins.css",
      "public/frontend/assets/css/style.css",
    ],
  'scss' => [

    ],
  'js' => [
    "public/frontend/assets/plugins/pubSub/jquery.pubSub.js",
    "public/frontend/assets/plugins/notifications/js/lobibox.min.js",
    "public/frontend/assets/plugins/notifications/js/notification-custom-script.js",
    "public/frontend/assets/plugins/notifications/js/notifications.min.js",
    "public/frontend/assets/js/stateManager.js",
    "public/frontend/assets/js/popper.js",
    "public/frontend/assets/js/bootstrap.min.js",
    "public/frontend/assets/js/owl.carousel.min.js",
    "public/frontend/assets/js/slick.min.js",
    "public/frontend/assets/js/jquery.magnific-popup.min.js",
    "public/frontend/assets/js/jquery.counterup.min.js",
    "public/frontend/assets/js/jquery.countdown.js",
    "public/frontend/assets/js/jquery.ui.js",
    "public/frontend/assets/js/jquery.elevatezoom.js",
    "public/frontend/assets/js/isotope.pkgd.min.js",
    "public/frontend/assets/js/slinky.menu.js",
    "public/frontend/assets/js/plugins.js",
    "public/frontend/assets/js/jquery.filter.js",
    "public/frontend/assets/js/jquery.sorting.js",
    "public/frontend/assets/js/jquery.checkout.js",
    "public/frontend/assets/js/jquery.emotions.js",
    "public/frontend/assets/js/jquery.quickview.js",
    "public/frontend/assets/js/jquery.basket.js",
    "public/frontend/assets/js/jquery.wishlist.js",
    "public/frontend/assets/js/jquery.paginator.js",
    "public/frontend/assets/js/jquery.loader.js",
    "public/frontend/assets/js/main.js",
    ],
);
?>
